<?php return
[
	'sanskrit'		=> '10',
	'hindi'		=> '11',
	'lipi12'		=> '12',
	'hinglish'		=> '14',
	'english'		=> '15',
	'arabic'		=> '16',
	'bengali'		=> '17',
	'mandarin'		=> '18',
	'french'		=> '19',
	'german'		=> '20',
	'japanese'		=> '21',
	'javanese'		=> '22',
	'korean'		=> '23',
	'punjabi'		=> '24',
	'portuguese'	=> '25',
	'russian' 		=> '26',
	'spanish' 		=> '27',
	'vietnamese'	=> '28',
	'urdu'		=> '29',
];
